### ISSUE TITLE
Incorrect poster image loads in cases where a movie has no poster (sometimes)

### ISSUE THREAD

**Issue by iffa** [roughike/inKino#65]
When selecting for example Turku Kinopalatsi from the nav drawer, initially the app shows the poster of "A Quiet Place" for "[rec]" as well. However if you scroll down and then up again (this I assume refreshes the view), "[rec]" with no poster renders correctly.

First screenshot shows the incorrect state and second screenshot is after you scroll a bit and let the view refresh.

![screenshot_20180411-233721](https://user-images.githubusercontent.com/759522/38642504-f17eca6a-3de2-11e8-812b-399c77bd3a66.png)

![screenshot_20180411-233741](https://user-images.githubusercontent.com/759522/38642505-f1a10bc0-3de2-11e8-8f9c-bb89b1a0b0c7.png)

PS. Sorry for the gigantic screenshots :D

**Comment by roughike** [comment]
Thanks for reporting!

**Comment by roughike** [comment]
*Update*: I think I know what might be causing this. By default, the selected theater is "All theaters", which currently has "A quiet place" as the first movie. Once you switch to "Turku: Kinopalatsi", the first movie changes to "[Rec]".

I was able to initially fix this by clearing the `EventState` from `nowInTheatersEvents` and `upcomingEvents`, but that results in the "No events available" empty view to be shown before animating to the loading indicator. I'll look if I can find the root cause. Maybe it's because of every model class not overriding the `hashCode` and `==` methods & all `StoreConnectors` being set to `distinct`.

**Comment by roughike** [comment]
I think this was fixed a while back. Not present with the latest version.

Thanks for reporting!
